// Package tjudge provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package tjudge

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// AuthToken defines model for AuthToken.
type AuthToken struct {
	// AccessToken JWT access token
	AccessToken string `json:"accessToken"`
}

// Error Error description
type Error struct {
	Message string `json:"message"`
}

// Team defines model for Team.
type Team struct {
	// Code Unique team code
	Code string `json:"code"`

	// Contest ID of the contest the team belongs to
	Contest int64         `json:"contest"`
	Leader  *UserResponse `json:"leader,omitempty"`

	// MaxSize Maximum team size
	MaxSize int `json:"maxSize"`

	// Members List of team members
	Members []UserResponse `json:"members"`

	// Name Team name
	Name string `json:"name"`
}

// TeamRegister defines model for TeamRegister.
type TeamRegister struct {
	// Code Unique team code
	Code string `json:"code"`

	// Contest ID of the contest the team belongs to
	Contest int64 `json:"contest"`

	// Leader ID of the team leader
	Leader *int64 `json:"leader,omitempty"`

	// MaxSize Maximum team size
	MaxSize *int `json:"maxSize,omitempty"`

	// Name Team name
	Name string `json:"name"`
}

// UserLogin defines model for UserLogin.
type UserLogin struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// UserRegister defines model for UserRegister.
type UserRegister struct {
	Fullname string `json:"fullname"`
	Password string `json:"password"`
	Username string `json:"username"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Fullname string `json:"fullname"`
	Id       int    `json:"id"`
	Username string `json:"username"`
}

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody = UserLogin

// PostRegisterJSONRequestBody defines body for PostRegister for application/json ContentType.
type PostRegisterJSONRequestBody = UserRegister

// RegisterTeamJSONRequestBody defines body for RegisterTeam for application/json ContentType.
type RegisterTeamJSONRequestBody = TeamRegister
